### PR TITLE
STOP POSTING ABOUT AMONG US!

### PR DESCRIPTION
**Pull request by SpeckyYT**
STOP POSTING ABOUT AMONG US! I'M TIRED OF SEEING IT! MY FRIENDS ON TIKTOK SEND ME MEMES, ON DISCORD IT'S FUCKING MEMES! I was in a server, right? and ALL OF THE CHANNELS were just among us stuff. I-I showed my champion underwear to my girlfriend and t-the logo I flipped it and I said "hey babe, when the underwear is sus HAHA DING DING DING DING DING DING DING DI DI DING" I fucking looked at a trashcan and said "THAT'S A BIT SUSSY" I looked at my penis I think of an astronauts helmet and I go "PENIS? MORE LIKE PENSUS" AAAAAAAAAAAAAAHGESFG

### CODE REVIEW

**Comment by itsmebombie** [comment]
STOP POSTING ABOUT spwn! I'M TIRED OF SEEING IT! MY FRIENDS ON TIKTOK SEND ME MEMES, ON DISCORD IT'S FUCKING MEMES! I was in a server, right? and ALL OF THE CHANNELS were just spwn stuff. I-I showed my champion underwear to my girlfriend and t-the logo I flipped it and I said "hey babe, when the underwear is blck HAHA where black where black where blck" I fucking looked at a trashcan and said "THAT'S A BIT blck" I looked at my penis I think of an astronauts helmet and I go "PENIS? MORE LIKE PENblck" AAAAAAAAAAAAAAHGESFG

**Comment by zTags** [comment]
START POSTING ABOUT AMONG US! I'M NOT TIRED OF SEEING IT! MY FRIENDS ON TIKTOK SEND ME MEMES, ON DISCORD IT'S FUCKING MEMES! I was in a server, right? and ALL OF THE CHANNELS were just among us stuff. I-I showed my champion underwear to my girlfriend and t-the logo I flipped it and I said "hey babe, when the underwear is sus HAHA DING DING DING DING DING DING DING DI DI DING" I fucking looked at a trashcan and said "THAT'S A BIT SUSSY" I looked at my penis I think of an astronauts helmet and I go "PENIS? MORE LIKE PENSUS" AAAAAAAAAAAAAAHGESFG

**Comment by qntm** [comment]
Base65536's usage of the "ඞ" character to encode binary data is not an Among Us reference and in fact predates that game by several years. Go take a walk.

**Comment by sertdfyguhi** [comment]
funy joke spcky

**Comment by itsmebombie** [comment]
funny joke qntm

**Comment by Fl1pNatic** [comment]
funny joke spcky

**Comment by SpeckyYT** [comment]
funny joke sertguhi

**Comment by sertdfyguhi** [comment]
funny joke spckyYT

**Pull request closed without merging**
